import "./globals.css";
import { Montserrat } from "next/font/google";
import Head from "./head";
import SignInButton from "./signInBtn";
import Provider from "@/comps/provider";
import Header from "@/comps/header";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Session } from "next-auth";
import { isNullishCoalesce } from "typescript";
const inter = Montserrat({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: Session | null = await getServerSession(authOptions)
  return (
    <html lang="en">
      {/* <Head /> */}
      <body className={`${inter.className}`}>
        <Provider>
          <Header session={session} />
          <main className="container mx-auto">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
