"use client";
import "./globals.css";
import { Montserrat, Vazirmatn } from "next/font/google";
import Provider from "@/comps/provider";
import Header from "@/app/header";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";
import { Session } from "next-auth";
import { MantineProvider, createEmotionCache } from "@mantine/core";
import rtlPlugin from "stylis-plugin-rtl";

const montserrat = Montserrat({ subsets: ["latin"], weight: ["400"] });
const vazir = Vazirmatn({ subsets: ["arabic"], weight: ["400"] });
export const metadata = {
  title: "کجا قسط",
  description: "Generated by create next app",
};
const rtlCache = createEmotionCache({
  key: "mantine-rtl",
  stylisPlugins: [rtlPlugin],
});
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
  testy: React.ReactNode;
}) {
  const links = [
    { label: "دسته بندی", link: "categories" },
    { label: "ارائه دهندگان", link: "providers" },
    { label: "آموزش", link: "learning" },
    { label: "درباره ما", link: "aboutus" },
  ];
  const session: Session | null = await getServerSession(authOptions);
  return (
    <html lang="en" dir="rtl">
      <body className={`${vazir.className} overflow-x-hidden`}>
        <MantineProvider
          withGlobalStyles
          withNormalizeCSS
          emotionCache={rtlCache}
          theme={{ dir: "rtl" }}
        >
          <Provider>
            <Header session={session} links={links} />
            <main className="container mx-auto">{children}</main>
          </Provider>
        </MantineProvider>
      </body>
    </html>
  );
}
